### ISSUE TITLE
Protect libp2p connection for handling query protocol.

### ISSUE THREAD

**Issue by hannahhoward** [filecoin-project/go-fil-markets#771] opened 2022-12-09 00:24 UTC

**Comment by rvagg** [comment] 2022-12-09 00:30
* https://github.com/filecoin-project/go-fil-markets/blob/cba436e47607d430b2012e232334f603b550a205/retrievalmarket/network/libp2p_impl.go#LL100C54-L100C54 ->
* https://github.com/filecoin-project/go-fil-markets/blob/cba436e47607d430b2012e232334f603b550a205/retrievalmarket/impl/provider.go#L328

Ref: https://github.com/application-research/filclient/pull/97 (the client side of this for autoretrieve)

**Comment by rvagg** [comment] 2022-12-09 02:26
closing because it's a dupe of -> #772

**Closed by rvagg** 2022-12-09 02:26 UTC
